CREATE DATABASE IF NOT EXISTS iltquiz;
USE iltquiz;

CREATE TABLE IF NOT EXISTS pergunta (
	id_perg INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pergunta TEXT,
    categoria INT,
    dica TEXT
);

CREATE TABLE IF NOT EXISTS resposta (
	id_resp INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fk_perg INT NOT NULL,
    CONSTRAINT fk_perg FOREIGN KEY (fk_perg) REFERENCES pergunta(id_perg),
    resposta TEXT,
    correta BOOL
);

INSERT INTO pergunta (id_perg, pergunta, categoria, dica) VALUES 
(10, 'Qual das seguintes ferramentas também eram utilizadas como arma branca?', 1, 'Não era o capacete e nem a matraca'),
(11, 'Onde, principalmente, eram utilizados os morteiros?', 1, 'Era um lugar protegido e não era em veículos'),
(12, 'Qual das seguintes armas tinha a função principal de defesa?', 1, 'Não era a pistola e nem lança-chamas'),
(13, 'Qual parte do exército utilizava rifles?', 1, 'Era a parte que andava a pé'),
(14, 'Qual das seguintes pistolas pertenceu a Primeira Guerra Mundial?', 1, 'Tem "8" em seu nome'),
(15, 'A granada de mão foi criada inicialmente para o uso de qual exército?', 1, 'Língua principal é o Inglês'),
(16, 'Qual era a carga explosiva da granada de mão?', 1, 'Não era a pólvora'),
(17, '', 1, ''),
(18, '', 1, ''),
(19, '', 1, ''),
(20, 'Qual foi o primeiro tanque de guerra utilizado na Primeira Guerra Mundial?', 2, 'Se chama Mark'),
(21, 'Para o transporte de armamentos eram utilizados, principalmente:', 2, 'Era blindado'),
(22, 'Qual foi o país que mais criou veículos blindados?', 2, 'O mesmo que foi pioneiro no uso de granadas'),
(23, 'Em 1917, os Estados unidos criaram seu primeiro tanque de guerra, seu nome era "Holt" 
devido à sua principal característica. Qual era essa característica?', 2, 'Tem relação com o seu combustível'),
(24, 'Qual foi a principal utilidade dos aviões durante a Primeira Guerra Mundial?', 2, 'Não foi o combate aéreo'),
(25, 'O reconhecimento foi uma importante função exercida pelos veículos aéreos. 
Qual das opções abaixo indica as suas três funções?', 2, 'Uma delas é a localização inimiga'),
(26, 'Os Zeppelin tem como principal função transportar pessoas, porém na Primeira Guerra 
Mundial os alemães o utilizavam para:', 2, 'Eles eram utilizados para atacar os inimigos'),
(27, 'São veículos da Primeira Guerra Mundial:', 2, 'O A7V é um deles'),
(28, 'Apesar de ter como principal foco o reconhecimento, os aviões também ajudaram nas batalhas com:', 2, 'Granadas'),
(29, 'A que eram movidos os veículos da Primeira Guerra Mundial?', 2, 'O mesmo combustível utilizado na revolução industrial'),
(30, 'A Primeira Guerra Mundial começou e terminou, respectivamente, em:', 3, 'Teve seu fim em 1918'),
(31, 'A "Tríplice Entente" foi uma aliança militar formada por quais países?', 3, 'A Inglaterra era um dos membros'),
(32, 'Qual foi o estopim para o começo da Primeira Guerra Mundial?', 3, 'Um assassinato'),
(33, 'Quais países saíram da Primeira Guerra Mundial como principais potências mundiais?', 3, 'São potências atualmente'),
(34, 'Para acessar a França, o exército alemão teve que passar pela Bélgica. Essa travessia 
foi muito violenta e ficou conhecida principalmente como:', 3, 'Tem "Bélgica" em seu nome'),
(35, 'Por qual motivo a Inglaterra declarou guerra à Alemanha?', 3, 'Não foi por causa de um acordo'),
(36, 'Por qual motivo o Brasil declarou guerra à Alemanha?', 3, 'O Brasil teve veículos abatidos'),
(37, 'A Primeira Guerra Mundial foi centrada em qual continente?', 3, 'Não foi nas Américas'),
(38, 'Qual foi o primeiro conflito da Primeira Guerra Mundial?', 3, 'Foi uma invasão'),
(39, 'Qual organização surgiu para evitar outro conflito desse nível?', 3, 'Possui "Liga" em seu nome'),
(40, 'Apenas um registro para evitar um bug', 4, 'Gambiarra');

INSERT INTO resposta (fk_perg, resposta, correta) VALUES 
(10, 'Capacete', false),
(10, 'Chave inglesa', false),
(10, 'Matraca', false),
(10, 'Pá de trincheira', true),
(11, 'Campos abertos', false),
(11, 'Construções', false),
(11, 'Trincheiras', true),
(11, 'Veículos', false),
(12, 'Metralhadora', true),
(12, 'Pistola', false),
(12, 'Rifle', false),
(12, 'Lança chamas', false),
(13, 'Blindados', false),
(13, 'Cavalaria', false),
(13, 'Infantaria', true),
(13, 'Artilharia', false),
(14, 'Glock P18C', false),
(14, 'Luger P08', true),
(14, 'Tecnam P92', false),
(14, 'AUG A3', false),
(15, 'Russo', false),
(15, 'Alemão', false),
(15, 'Inglês', true),
(15, 'Chinês', false),
(16, 'Péricles', false),
(16, 'Glicerina', false),
(16, 'Baratol', true),
(16, 'Pólvora', false),
(17, '', 1),
(18, '', 1),
(19, '', 1),
(20, 'Mark I', true),
(20, 'Renault FT', false),
(20, 'Mark II', false),
(20, 'Char 2C', false),
(21, 'Carros armados', false),
(21, 'Trens blindados', true),
(21, 'Aviões com escolta armada', false),
(21, 'Nenhuma das opções', false),
(22, 'Itália', false),
(22, 'Alemanha', false),
(22, 'Reino Unido', true),
(22, 'França', false),
(23, 'Foi o maior tanque desenvolvido', false),
(23, 'Era movido a vapor', false),
(23, 'Era muito leve pois possuía uma estrutura esquelética', false),
(23, 'Era movido a gás', true),
(24, 'Combate aéreo', false),
(24, 'Bombardeio', false),
(24, 'Destruição de veículos', false),
(24, 'Reconhecimento', true),
(25, 'Reconhecimento fotográfico, localização inimiga e patrulha de contato', true),
(25, 'Reconhecimento de veículos blindados, localização inimiga e patrulha de contato', false),
(25, 'Reconhecimento fotográfico, localização inimiga e patrulha de bombardeio', false),
(25, 'Reconhecimento fotográfico, assistência combatendo inimigos e patrulha de contato', false),
(26, 'Reconhecimento', false),
(26, 'Transporte de soldados', false),
(26, 'Transporte de armas', false),
(26, 'Bombardeio', true),
(27, 'A7V, Char 2C e Mark I', true),
(27, 'Mark I, Holt e Universal Carrier', false),
(27, 'Holt, Char 2C e Somua S35', false),
(27, 'Char 2C, A7V e Matilda A12', false),
(28, 'Granadas, morteiros e tijolos', true),
(28, 'Facas, morteiros e granadas', false),
(28, 'Bomba de fumaça, facas e morteiros', false),
(28, 'Tijolos, granadas e bomba de fumaça', false),
(29, 'Etanol', false),
(29, 'Gasolina', false),
(29, 'Vapor', true),
(29, 'Água', false),
(30, '1912 - 1916', false),
(30, '1914 - 1918', true),
(30, '1916 - 1920', false),
(30, '1910 - 1918', false),
(31, 'França, EUA e Alemanha', false),
(31, 'EUA, Rússia e Império Otomano', false),
(31, 'Inglaterra, França e Alemanha', false),
(31, 'Inglaterra, França e Rússia', true),
(32, 'O assassinato de Francisco Ferdinando', true),
(32, 'A invasão dos EUA à Alemanha', false),
(32, 'A busca desenfreada por territórios', false),
(32, 'Nenhuma das opções', false),
(33, 'Estados Unidos e França', false),
(33, 'Japão e França', false),
(33, 'Japão e Itália', false),
(33, 'Estados Unidos e Japão', true),
(34, 'O massacre da Bélgica', false),
(34, 'A grande devastação belga', false),
(34, 'O estupro da Bélgica', true),
(34, 'Nenhuma das opções', false),
(35, 'O acordo que a Alemanha tinha com os EUA', false),
(35, 'Retomada de territórios conquistados pela Alemanha', false),
(35, 'O ataque da Alemanha à Bélgica', true),
(35, 'O acordo que a Alemanha tinha com os EUA', false),
(36, 'A Inglaterra entrou na guerra', false),
(36, 'Submarinos brasileiros foram abatidos por corvetas alemãs', false),
(36, 'Os EUA entraram na guerra', false),
(36, 'Navios mercantes brasileiros foram abatidos por submarinos alemães', true),
(37, 'Europa', true),
(37, 'América do Sul', false),
(37, 'América do Norte', false),
(37, 'Ásia', false),
(38, 'Guerra dos sete anos', false),
(38, 'Invasão franco-canadense à Alemanha', false),
(38, 'Guerra dos sete dias', false),
(38, 'Invasão austro-húngara à Sérvia', true),
(39, 'A Liga Anti-Guerra', false),
(39, 'A Liga das Nações', true),
(39, 'Organização da paz', false),
(39, 'Organização Mundial', false);